### ISSUE TITLE
dedicated_server_boot boot ids incorrect for ovh-us

### ISSUE THREAD

**Issue by m-sarti** [synthesio/infra-ovh-ansible-module#101]
In the ovh-us endpoint the boot id mapping differs from ovh-eu: trying to call the dedicated_server_boot module for rescue mode results in the following error:

`ovh.exceptions.ResourceNotFoundError: Netboot id 46371 is not valid, must be on list : 6, 182, 1818, 1, 86152, 191853, 39720, 14, 7`

The decoding in the code is as follows:

`bootid = {'harddisk': 1, 'rescue-customer': 46371, 'ipxe-shell': 203323, 'poweroff': 95083}`

In this sense it would be preferable if the module directly accepted the boot ID in addition to the 'boot' parameter.

**Comment by tortuegenialez** [comment]
Hi,
Could you confirm that #103 fixes the issue, please?
