### ISSUE TITLE
reverse service miss ipBlock parameter

### ISSUE THREAD

**Issue by fraff** [synthesio/infra-ovh-ansible-module#13]
Hi,

https://api.ovh.com/console/#/ip/%7Bip%7D/reverse#POST needs 2 parameters, ipBlock and ip. They are identicals on cloud machines or failover IP but they are not on vrack IPs block (https://api.ovh.com/console/#/vrack/%7BserviceName%7D/ip/%7Bip%7D#GET)

Please, add an ipBlock option with default to 'ip' in https://github.com/synthesio/infra-ovh-ansible-module/blob/master/plugins/modules/ovh.py#L343

**Comment by fraff** [comment]
any news ?

**Comment by Skunnyk** [comment]
Hi. We don't really use the reverse module for vrack blocks, but #24 should help you :)

**Comment by fraff** [comment]
@Skunnyk thanks a lot
