### ISSUE TITLE
DNS CNAME records

### ISSUE THREAD

**Issue by hmrodrigues** [synthesio/infra-ovh-ansible-module#4]
Hello,

It would be nice to be able to set CNAME records instead of only A records.

Best Regards,
Hugo Rodrigues

**Comment by Skunnyk** [comment]
Now that the collection has been rewritten and is modular, you should be able to enhance `domain.py` (or create a new endpoint) to handle DNS stuff :)

**Comment by ajdelgado** [comment]
I have a branch in a forker repo to include other records (I started with CNAME since I also need it) but I'm missing something because I can't make it work. Any help to fix it will be appreciated.

**Comment by xtof-osd** [comment]
> I have a branch in a forked repo https://github.com/ajdelgado/infra-ovh-ansible-module/tree/4-add-more-record-types to include other records (I started with CNAME since I also need it) but I'm missing something because I can't make it work. Any help to fix it will be appreciated.

Hi, I did the job on a previous version of infra-ovh-ansible-module (see the fork on my profile), but it never got merged because the team refactored the module since. It may be useful, as I use it on a daily basis, I know it works.

**Comment by ajdelgado** [comment]
> 
> 
> I have a branch in a forked repo https://github.com/ajdelgado/infra-ovh-ansible-module/tree/4-add-more-record-types to include other records (I started with CNAME since I also need it) but I'm missing something because I can't make it work. Any help to fix it will be appreciated.

Actually my branch work (I didn't switched the branch when I tested :P ) to create CNAME records, but I didn't test the rest.

**Comment by Skunnyk** [comment]
Fixed with #26
