### ISSUE TITLE
Use SOPS to read configuration ?

### ISSUE THREAD

**Issue by nipil** [synthesio/infra-ovh-ansible-module#94]
Would it be possible to use SOPS to transparently load the configuration from an encrypted `/etc/ovh.sops.conf` ?

**Comment by tortuegenialez** [comment]
I don't think so, the authentication is made by the [python-ovh](https://github.com/ovh/python-ovh?tab=readme-ov-file#configuration) module directly wich reads
```
    Current working directory: ./ovh.conf
    Current user's home directory ~/.ovh.conf
    System wide configuration /etc/ovh.conf
```

**Comment by nipil** [comment]
After a little searching i read that OVH library handles environment variables too

So i can directly load secerts into environment variables
And even load them from SOPS protected file like below

With `ovh.sops.env` as a text file containing

```
OVH_ENDPOINT=ovh-eu
OVH_APPLICATION_ID=111111
OVH_APPLICATION_KEY=aaaaaaaaaaaaaaaa
OVH_APPLICATION_SECRET=bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
OVH_CONSUMER_KEY=cccccccccccccccccccccccccccccccc
```

I can run `sops exec-env ovh.sops.env "ansible..."` to load env vars securely before running ansible command

That ought to do it, thanks !
